doc_search_task:
  description: "Answer the customer's questions based on the attention PDF.
    The research agent will search through the PDF to find relevant answers.
    Your final answer MUST be clear and accurate, based on the content of the
    attention PDF.
    Here is the customer's question:
    {input_query}"
  expected_output:
    "Provide clear and accurate answers to the customer's questions based on the content of the attention PDF.
    Write the answer in the output file."
